// swift-tools-version:5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
	name: "SwiftlaneCore",
	platforms: [.macOS(.v12)],
	products: [
		/// Umbrella target.
		///
		/// Instead of doing this:
		///
		///		import SwiftlanePaths
		///		import SwiftlaneLogging
		///		import SwiftlaneCoreServices
		///		import SwiftlaneShell
		///		import SwiftlaneExtensions
		///
		/// You can do this:
		///
		///		import SwiftlaneCore
		///
		.library(name: "SwiftlaneCore", targets: ["SwiftlaneCore"]),
		
		.library(name: "SwiftlanePaths", targets: ["SwiftlanePaths"]),
		.library(name: "SwiftlaneLogging", targets: ["SwiftlaneLogging"]),
		.library(name: "SwiftlaneCoreServices", targets: ["SwiftlaneCoreServices"]),
		.library(name: "SwiftlaneShell", targets: ["SwiftlaneShell"]),
		.library(name: "SwiftlaneExtensions", targets: ["SwiftlaneExtensions"]),
		
		/// Contains usefull stuff for unit testing.
		.library(name: "SwiftlaneUnitTestTools", targets: ["SwiftlaneUnitTestTools"]),
		
		/// Сontains mocks for this package **generated by SwiftyMocky**.
		.library(name: "SwiftlaneCoreMocks", targets: ["SwiftlaneCoreMocks"]),
	],
	dependencies: [
		.package(url: "https://github.com/nstmrt/PerfectRainbow", from: "4.0.2"),
		.package(url: "https://github.com/nstmrt/SwiftyMocky.git", from: "4.1.1"),
	],
	targets: [

		// MARK: Products targets
		
		.target(name: "SwiftlaneCore", dependencies: [
			"SwiftlanePaths",
			"SwiftlaneLogging",
			"SwiftlaneCoreServices",
			"SwiftlaneShell",
			"SwiftlaneExtensions",
		]),
		.target(name: "SwiftlaneExtensions", dependencies: [
			"PerfectRainbow",
		]),
		.target(name: "SwiftlaneLogging", dependencies: [
			"SwiftlaneExtensions",
			"PerfectRainbow",
		]),
		.target(name: "SwiftlaneCoreServices", dependencies: [
			"SwiftlaneExtensions",
			"SwiftlaneLogging",
			"PerfectRainbow",
		]),
		.target(name: "SwiftlanePaths", dependencies: [
			"SwiftlaneLogging",
			"SwiftlaneExtensions",
			"SwiftlaneCoreServices",
		]),
		.target(name: "SwiftlaneShell", dependencies: [
			"SwiftlaneExtensions",
			"SwiftlaneLogging",
			"SwiftlanePaths",
			"SwiftlaneCoreServices",
			"PerfectRainbow",
		]),
		.target(name: "SwiftlaneUnitTestTools", dependencies: [
			"SwiftlaneExtensions",
			"SwiftlaneLogging",
			"SwiftlaneCoreServices",
			"SwiftlanePaths",
			"PerfectRainbow",
		]),
		
		// MARK: Unit Tests
		
		.target(name: "SwiftlaneCoreMocks", dependencies: [
			"SwiftlanePaths",
			"SwiftlaneLogging",
			"SwiftlaneCoreServices",
			"SwiftlaneShell",
			"SwiftlaneExtensions",
			"PerfectRainbow",
			"SwiftyMocky",
		]),
		
		.testTarget(name: "SwiftlaneExtensionsTests", dependencies: [
			"SwiftlaneExtensions",
			"SwiftlaneUnitTestTools",
			"SwiftlaneCoreMocks",
			"SwiftyMocky",
		]),
		.testTarget(name: "SwiftlaneLoggingTests", dependencies: [
			"SwiftlaneLogging",
			"SwiftlaneUnitTestTools",
			"SwiftlaneCoreMocks",
			"SwiftyMocky",
		]),
		.testTarget(name: "SwiftlaneCoreServicesTests", dependencies: [
			"SwiftlaneCoreServices",
			"SwiftlaneUnitTestTools",
			"SwiftlaneCoreMocks",
			"SwiftyMocky",
		]),
		.testTarget(name: "SwiftlanePathsTests", dependencies: [
			"SwiftlanePaths",
			"SwiftlaneUnitTestTools",
			"SwiftlaneCoreMocks",
			"SwiftyMocky",
		]),
		.testTarget(name: "SwiftlaneShellTests", dependencies: [
			"SwiftlaneShell",
			"SwiftlaneUnitTestTools",
			"SwiftlaneCoreMocks",
			"SwiftyMocky",
		]),
	]
)
